import Login from "./login";

export const metadata = {
  title: "Login | Ecom Boilerplate",
  description: "Generated by Chase Mack",
};

export default function LoginPage() {
  return (
    <main>
      <Login />
    </main>
  );
}
