export const metadata = {
  title: "Cart | Ecom Boilerplate",
  description: "Generated by Chase Mack",
};

export default function CartLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <h1>This is the Cart</h1>
    </main>
  );
}
