import Cart from "./cart";

export const metadata = {
  title: "Cart | Ecom Boilerplate",
  description: "Generated by Chase Mack",
};

export default function CartPage() {
  return (
    <main>
      <Cart />
    </main>
  );
}
