/* eslint-disable @next/next/no-img-element */
import "./globals.css";
import styles from "@/app/layout.module.css";
import Header from "./common/header/header";
import Footer from "./common/footer/footer";

export const metadata = {
  title: "ECom Boilerplate",
  description: "Generated by Chase Mack",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
