import styles from "./layout.module.css";
import Products from "./products";
import { use } from "react";

export const metadata = {
  title: "Products | Ecom Boilerplate",
  description: "Generated by Chase Mack",
};

export default async function ProductsLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const products = await getProductData();
  return (
    <main>
      <h1>This is the Products Page</h1>
      {products ? <Products products={products} /> : null}
    </main>
  );
}

function getProductData() {
  return fetch("https://fakestoreapi.com/products").then((res) => res.json());
}
