import Signup from "./signup";

export const metadata = {
  title: "Signup | Ecom Boilerplate",
  description: "Generated by Chase Mack",
};

export default function SignupPage() {
  return (
    <main>
      <Signup />
    </main>
  );
}
